### ISSUE TITLE
Quick Setting Tile Doesn't Dismiss Notification Shade

### ISSUE THREAD

**Issue by locuturus** [JonasBernard/FakeStandby#67]
Hello,

Version 1.4.0 works for me except that the notification shade remains open after I blank the screen from the quick setting tile. I can see it is still open after I escape the screen blanking. This is a problem in a few apps which detect the notification shade is visible and change their behavior.

1.3.3 was the last version that I know both A) worked at all for me and B) dismissed the notification shade during activation. One or two versions after 1.3.3 crashed immediately so I'm not sure what they would have done with the notification shade.

Tested on Google Pixel 4a and Sony Xperia 5 iii and both are on Android 13.

**Comment by JonasBernard** [comment]
Version 1.3.3 targeted an older SDK and worked fine.
The version 1.3.4 and 1.3.5 were targeting a newer SDK (aka. Android version) and tried to close the navigation drawer and crashed because the newer version of Android do not support closing it.

In version 1.4.0 I removed the function that tries to close the navigation drawer. That's why it 1.4.0 works again and does not crash.

Unless I can find an alternative way to close the drewer, this will not work, I'm sorry, I can't do anything about Android features.

From time to time I target newer SDK versions to keep the app up to date and running on newer phones.

**Comment by locuturus** [comment]
You already use accessibility services, have you tried:
`GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE` 
action from AccessibilityService? This is recommended by Google in Android 12+ and replaces
`ACTION_CLOSE_SYSTEM_DIALOGS` intent. It's way overkill for most apps but you already need accessibility services anyway.
